name: Publish Beta

on:
  workflow_dispatch:
    # Inputs the workflow accepts.
    inputs:
      git-ref:
        description: 'Git Ref'
        default: 'beta'
        required: false

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2.3.1
        with:
          branch: ${{ github.events.inputs.git-ref }}
      - uses: actions/setup-node@v2.1.0
        with:
          node-version: 10
      - name: npm install and build
        run: |
          npm ci
          npm run build --if-present
        env:
          CI: true

  publish-npm:
    if: github.repository == 'Sunoo/homebridge-camera-ffmpeg'

    needs: build

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2.3.1
      - uses: actions/setup-node@v2.1.0
        with:
          node-version: 10
          registry-url: https://registry.npmjs.org/
      - run: npm ci
      - run: node .github/workflows/prerelease.js
      - run: npm --no-git-tag-version version prerelease --preid=beta
      - run: npm publish --tag=beta
        env:
          NODE_AUTH_TOKEN: ${{secrets.npm_token}}
